### ISSUE TITLE
Error: WebSocketChannelException

### ISSUE THREAD

**Issue by maxbrito500** [ethicnology/dispute#11] opened 2023-05-17 14:10 UTC
Hello,

Can you please update the version available by default on the Ubuntu store?

The older version is still available there and giving error when installing.

Thanks!

**Comment by ethicnology** [comment] 2023-05-19 09:54
@maxbrito500 Hi, the error does not come from code but from my personal relay: https://relay.dispute.systems which was down.
Since I'm not actively developing this app I will soon shut down my relay to avoid paying for a server + domain name.

Anyway, you can still connect to the relay of your choice in the settings, there are lists of available relay:
- [nostr.info](https://nostr.info/relays/)
- [nostr.watch](https://nostr.watch/relays/find)

PS: Since the app does not have data persistency and lack of lot of features, may i ask you what is your main usage for it, same for the relay which was designed to test the app ?

**Comment by maxbrito500** [comment] 2023-05-19 23:22
Hello, thanks.

This is currently the only nostr app on the Ubuntu software app. I'm a nostr user and would prefer to use the desktop than the web browser versions. Did not know it was just a test app.

**Comment by ethicnology** [comment] 2023-05-20 07:42
Since there is no data persistency, it means that each time you run the app you paste your own private key and relay to use the app ?

**Comment by maxbrito500** [comment] 2023-05-20 09:56
Didn't started using yet because it seemed broke.

Anyways you've lost interest in continuing the app?

I'm looking at the code, wish I could help adding those missing features but seems a bit out of my reach.

**Comment by ethicnology** [comment] 2023-05-21 07:26
> Didn't started using yet because it seemed broke.

The server is up, but there is no-one speeking on this relay since it was used mainly for development.
I will shut-it down soon.

> Anyways you've lost interest in continuing the app?

Time is a scarce resource, I have others projects but more than this, even if I love Free Software, I'm dedicating too much time to it regarding the fact that I need money to survive. My wish is to find a way to earn my life while working on cool open-source/free projects.

The current status of this project is the same as the library, **maintained**. If there are new contributions, I will review, rework and help the contributor to finish the job properly. I will not implement new features myself. Free software is a common good that we should focus on to avoid each individual to waste their time on their own package. I hope there will be new contributors that will give their time to implement clean features for our peers, [see](https://github.com/ethicnology/dart-nostr/issues/15).

**Comment by ethicnology** [comment] 2023-05-21 10:12
I pushed a new [version](https://github.com/ethicnology/dispute/releases/tag/v1.1.3)  of dispute which does not rely anymore on my dev relay, relay.dispute.systems.

At the starting of the app you can set a relay such as `wss://nos.lol` or any other compatible [nostr relay](https://nostr.info/relays/).

I'm closing the issue but do not hesitate to pursue the conversation here or somewhere else.

**Closed by ethicnology** 2023-05-21 10:12 UTC

**Comment by maxbrito500** [comment] 2023-05-24 10:21
Can you please also update the new version into the software center at Ubuntu? It would help to have a working experience for those installing it new.
